remote_theme: "mmistakes/minimal-mistakes@4.16.0"

plugins:
  - jekyll-include-cache


layout: single
logo: AdventureCorpLogo.png

---
layout: splash
permalink: /
header:
  overlay_color: "#5e616c"
  overlay_image: AdventureCorpLogo.png
  actions:
    - label: "<i class='fas fa-download'></i> Install now"
      url: "/"
excerpt: >
  A flexible two-column Jekyll theme. Perfect for building personal sites, blogs, and portfolios.<br />
  <small><a href="https://github.com/mmistakes/minimal-mistakes/releases/tag/4.16.0">Latest release v4.16.0</a></small>
feature_row:
  - image_path: AdventureCorpLogo.png
    alt: "customizable"
    title: "Super customizable"
    excerpt: "Everything from the menus, sidebars, comments, and more can be configured or set with YAML Front Matter."
    url: "/"
    btn_class: "btn--primary"
    btn_label: "Learn more"
  - image_path: AdventureCorpLogo.png
    alt: "fully responsive"
    title: "Responsive layouts"
    excerpt: "Built with HTML5 + CSS3. All layouts are fully responsive with helpers to augment your content."
    url: "/"
    btn_class: "btn--primary"
    btn_label: "Learn more"
  - image_path: AdventureCorpLogo.png
    alt: "100% free"
    title: "100% free"
    excerpt: "Free to use however you want under the MIT License. Clone it, fork it, customize it... whatever!"
    url: "/"
    btn_class: "btn--primary"
    btn_label: "Learn more"      
---

{% include feature_row %}
